# Lab 1

# Setup

In [2]:
# Setup
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

from chop.tools import get_tokenized_dataset

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)

INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.

#

In [3]:

import torch.nn as nn
from chop.nn.modules import Identity

search_space = {
    "num_layers": [2, 4, 8],
    "num_heads": [2, 4, 8, 16],
    "hidden_size": [128, 192, 256, 384, 512],
    "intermediate_size": [512, 768, 1024, 1536, 2048],
    "linear_layer_choices": [
        nn.Linear,
        Identity,
    ],
}

# model constructor

from transformers import AutoConfig, AutoModelForSequenceClassification
from chop.tools.utils import deepsetattr

def construct_model(trial):
    config = AutoConfig.from_pretrained(checkpoint)

    # Update the paramaters in the config
    for param in [
        "num_layers",
        "num_heads",
        "hidden_size",
        "intermediate_size",
    ]:
        chosen_idx = trial.suggest_int(param, 0, len(search_space[param]) - 1)
        print("chosen_idx = ", chosen_idx)
        print("search_space[param][chosen_idx]", search_space[param][chosen_idx])
        setattr(config, param, search_space[param][chosen_idx])

    trial_model = AutoModelForSequenceClassification.from_config(config)

    for name, layer in trial_model.named_modules():
        if isinstance(layer, nn.Linear) and layer.in_features == layer.out_features:
            new_layer_cls = trial.suggest_categorical(
                f"{name}_type",
                search_space["linear_layer_choices"],
            )

            if new_layer_cls == nn.Linear:
                continue
            elif new_layer_cls == Identity:
                new_layer = Identity()
                deepsetattr(trial_model, name, new_layer)
            else:
                raise ValueError(f"Unknown layer type: {new_layer_cls}")

    return trial_model

# Compression Aware Search

In [ ]:
import copy

quantization_config = {
    "by": "type",
    "default": {
        "config": {
            "name": None,
        }
    },
    "linear": {
        "config": {
            "name": "integer",
            # data
            "data_in_width": 8,
            "data_in_frac_width": 4,
            # weight
            "weight_width": 8,
            "weight_frac_width": 4,
            # bias
            "bias_width": 8,
            "bias_frac_width": 4,
        }
    },
}

pruning_config = {
    "weight": {
        "sparsity": 0.5,
        "method": "l1-norm",
        "scope": "local",
    },
    "activation": {
        "sparsity": 0.5,
        "method": "l1-norm",
        "scope": "local",
    },
}

compression_config = {
    "quantize_transform_pass": quantization_config,
    "prune_transform_pass": pruning_config,
}


from chop.pipelines import CompressionPipeline
from chop import MaseGraph
import os

pipe = CompressionPipeline()


evals_1 = []
evals_2 = []
evals_3 = []

# Trainer
from chop.tools import get_trainer


def objective(trial):
    print("trial config: ", trial.params)
    # Define the model
    model = construct_model(trial)
    print("trial config: ", trial.params)
    
    # 3 
    # s in total, run trainer.train() twice
    trainer = get_trainer(
        model=model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
        num_train_epochs=5,
    )

    # Stage 1: No Compression - just training
    trainer.train()
    eval_results_1 = trainer.evaluate()
    ## Store the results
    evals_1.append((trial.params, eval_results_1["eval_accuracy"]))

    # Stage 2: Compression Aware (no Post Compression Training)
    # Move model to CPU and create MaseGraph for compression
    model.cpu()
    mg = MaseGraph(model)
    # Use a deep copy of compression_config to avoid mutation across trials
    mg, _ = pipe(mg, copy.deepcopy(compression_config))
    # Move model back to CUDA for evaluation
    model.cuda()
    eval_results_2 = trainer.evaluate()
    ## Store the results
    evals_2.append((trial.params, eval_results_2["eval_accuracy"]))

    # Stage 3: Compression Aware (with QAT)
    trainer.train()
    eval_results_3 = trainer.evaluate()
    ## Store the results
    evals_3.append((trial.params, eval_results_3["eval_accuracy"]))

    # Set the model as an attribute so we can fetch it later
    trial.set_user_attr("model", model)

    return eval_results_3["eval_accuracy"]


from optuna.samplers import GridSampler, RandomSampler, TPESampler

sampler = RandomSampler()

import optuna

study = optuna.create_study(
    direction="maximize",
    study_name="bert-tiny-nas-study",
)

study.optimize(
    objective,
    n_trials=20,
    timeout=60 * 60 * 24,
)

[I 2026-02-02 23:28:05,807] A new study created in memory with name: bert-tiny-nas-study

trial config:  {}
chosen_idx =  1
search_space[param][chosen_idx] 4
chosen_idx =  2
search_space[param][chosen_idx] 8
chosen_idx =  0
search_space[param][chosen_idx] 128
chosen_idx =  4
search_space[param][chosen_idx] 2048

/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

trial config:  {'num_layers': 1, 'num_heads': 2, 'hidden_size': 0, 'intermediate_size': 4, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.
INFO     Getting dummy input for prajjwal1/bert-tiny.
INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: classifier

tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.7192, -1.4301,  0.1715,  ...,  1.0948, -1.6365,  0.9650],
         [-1.9657,  0.1727,  0.7456,  ...,  1.1198, -0.9969,  0.9112],
         ...,
         [-0.4332, -1.1145,  1.4794,  ...,  0.1403, -2.2722,  1.6160],
         [-1.6353, -1.5800,  0.9595,  ...,  0.2225, -0.1600,  0.2488],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]],

        [[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.1626, -1.7460, -0.1859,  ...,  1.8125, -2.3404,  1.1401],
         [-1.0802, -1.6798,  2.1436,  ...,  1.1471, -0.6465,  1.4981],
         ...,
         [ 1.1359, -1.1523, -0.0819,  ...,  0.1204, -1.2642,  1.8203],
         [-1.1290, -1.1690,  0.3605,  ...,  0.4243, -0.1978,  0.6577],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[ 1.6034, -1.2145,  0.8713,  ...,  1.7689, -1.3327, -1.2377],
         [ 0.6641, -0.3469,  0.5967,  ...,  0.8922, -0.9442, -0.8660],
         [ 0.9761, -0.5886,  0.6120,  ...,  0.5117, -1.1629, -0.7543],
         ...,
         [ 0.3700, -0.1626,  0.4242,  ...,  0.6086, -0.4187, -0.8024],
         [ 0.3095, -0.1795,  0.3237,  ...,  0.6352, -0.6532, -0.5623],
         [ 0.6210, -0.1428,  0.5131,  ...,  0.9695, -1.0532, -0.4868]],

        [[ 1.6034, -1.2145,  0.8713,  ...,  1.7689, -1.3327, -1.2377],
         [ 0.3063,  0.1540,  0.2985,  ...,  0.5060, -0.3992, -0.1518],
         [ 0.5773, -0.5170,  0.4225,  ...,  0.3058, -0.9796, -0.7433],
         ...,
         [ 0.3359, -0.3930,  0.3661,  ...,  0.6219, -0.1977, -0.9480],
         [ 0.4390, -0.3657,  0.4706,  ...,  0.4283, -0.8055, -0.6866],
         [ 0.6210, -0.1428,  0.5131,  ...,  0.9695, -1.0532, -0.4868]]],
       grad_fn=<ViewBackward0>)
tensor([[[ 1.6034, -1.2145,  0.8713,  ...,  1.7689, -1.3327, -1.2377],
         [ 0.6641, -0.3469,  0.5967,  ...,  0.8922, -0.9442, -0.8660],
         [ 0.9761, -0.5886,  0.6120,  ...,  0.5117, -1.1629, -0.7543],
         ...,
         [ 0.3700, -0.1626,  0.4242,  ...,  0.6086, -0.4187, -0.8024],
         [ 0.3095, -0.1795,  0.3237,  ...,  0.6352, -0.6532, -0.5623],
         [ 0.6210, -0.1428,  0.5131,  ...,  0.9695, -1.0532, -0.4868]],

        [[ 1.6034, -1.2145,  0.8713,  ...,  1.7689, -1.3327, -1.2377],
         [ 0.3063,  0.1540,  0.2985,  ...,  0.5060, -0.3992, -0.1518],
         [ 0.5773, -0.5170,  0.4225,  ...,  0.3058, -0.9796, -0.7433],
         ...,
         [ 0.3359, -0.3930,  0.3661,  ...,  0.6219, -0.1977, -0.9480],
         [ 0.4390, -0.3657,  0.4706,  ...,  0.4283, -0.8055, -0.6866],
         [ 0.6210, -0.1428,  0.5131,  ...,  0.9695, -1.0532, -0.4868]]],
       grad_fn=<ViewBackward0>)
tensor([[[[ 1.6034e+00, -1.2145e+00,  8.7135e-01,  ...,  1.7191e+00,
            1.1471e+00,  8.2107e-01],
          [-1.7106e-01,  5.7876e-01, -2.3489e-01,  ...,  1.7689e+00,
           -1.3327e+00, -1.2377e+00]],

         [[ 6.6413e-01, -3.4695e-01,  5.9666e-01,  ...,  6.9335e-01,
            7.4750e-01,  7.0258e-03],
          [-2.8131e-01,  2.4176e-01, -1.3108e-01,  ...,  8.9225e-01,
           -9.4416e-01, -8.6604e-01]],

         [[ 9.7606e-01, -5.8855e-01,  6.1201e-01,  ...,  4.5344e-01,
            5.2582e-01,  3.4820e-01],
          [ 1.9651e-01,  8.5391e-01,  2.8816e-01,  ...,  5.1165e-01,
           -1.1629e+00, -7.5428e-01]],

         ...,

         [[ 3.7004e-01, -1.6259e-01,  4.2423e-01,  ...,  5.6279e-01,
            1.3386e-01,  6.9196e-03],
          [-2.5644e-01,  1.3190e-01, -2.6929e-01,  ...,  6.0857e-01,
           -4.1868e-01, -8.0243e-01]],

         [[ 3.0950e-01, -1.7955e-01,  3.2370e-01,  ...,  2.2032e-01,
            4.6783e-01, -8.4258e-02],
          [ 2.2451e-02,  7.1986e-01, -2.2503e-01,  ...,  6.3522e-01,
           -6.5321e-01, -5.6226e-01]],

         [[ 6.2102e-01, -1.4275e-01,  5.1309e-01,  ...,  5.3747e-01,
            4.1893e-04, -4.5869e-02],
          [-2.5588e-01,  6.9964e-01, -1.5778e-01,  ...,  9.6955e-01,
           -1.0532e+00, -4.8678e-01]]],


        [[[ 1.6034e+00, -1.2145e+00,  8.7135e-01,  ...,  1.7191e+00,
            1.1471e+00,  8.2107e-01],
          [-1.7106e-01,  5.7876e-01, -2.3489e-01,  ...,  1.7689e+00,
           -1.3327e+00, -1.2377e+00]],

         [[ 3.0626e-01,  1.5402e-01,  2.9850e-01,  ...,  8.3620e-01,
            3.5084e-01, -1.4118e-01],
          [-1.8432e-01,  8.6388e-02,  3.4859e-03,  ...,  5.0603e-01,
           -3.9923e-01, -1.5181e-01]],

         [[ 5.7731e-01, -5.1703e-01,  4.2250e-01,  ...,  4.5600e-01,
            6.1690e-01,  1.3188e-01],
          [ 7.1370e-02,  6.7304e-01,  2.1330e-01,  ...,  3.0579e-01,
           -9.7961e-01, -7.4333e-01]],

         ...,

         [[ 3.3588e-01, -3.9295e-01,  3.6612e-01,  ...,  6.8730e-01,
            2.3036e-01, -2.1039e-02],
          [-4.2176e-01, -7.3541e-02, -4.6237e-01,  ...,  6.2195e-01,
           -1.9775e-01, -9.4802e-01]],

         [[ 4.3901e-01, -3.6573e-01,  4.7064e-01,  ...,  2.6409e-01,
            3.0585e-01, -1.5744e-02],
          [ 6.1704e-02,  4.7518e-01, -3.0585e-01,  ...,  4.2825e-01,
           -8.0549e-01, -6.8660e-01]],

         [[ 6.2102e-01, -1.4275e-01,  5.1309e-01,  ...,  5.3747e-01,
            4.1893e-04, -4.5869e-02],
          [-2.5588e-01,  6.9964e-01, -1.5778e-01,  ...,  9.6955e-01,
           -1.0532e+00, -4.8678e-01]]]], grad_fn=<ViewBackward0>)
tensor([[[-0.2005,  0.4112, -0.2872,  ...,  0.1290,  0.4514,  0.3414],
         [-0.1999,  0.0860, -0.5153,  ...,  0.3916,  0.4107,  0.2008],
         [-0.2135,  0.5551, -0.5168,  ..., -0.1322,  0.4070,  0.4075],
         ...,
         [-0.3215,  0.1026, -0.2454,  ...,  0.2533,  0.5222,  0.2528],
         [-0.0363, -0.2433, -0.2383,  ...,  0.4081,  0.4931,  0.2604],
         [-0.0416,  0.1293,  0.1484,  ...,  0.0925,  0.2657,  0.3371]],

        [[-0.2005,  0.4112, -0.2872,  ...,  0.1290,  0.4514,  0.3414],
         [-0.3425,  0.2470, -0.4488,  ..., -0.1035,  0.4190,  0.5254],
         [-0.4660,  0.2110,  0.0730,  ...,  0.0310,  0.6527,  0.4932],
         ...,
         [-0.3491, -0.0945, -0.4201,  ...,  0.2475,  0.5849,  0.3557],
         [ 0.0488, -0.0947, -0.4573,  ...,  0.6100,  0.3797,  0.3675],
         [-0.0416,  0.1293,  0.1484,  ...,  0.0925,  0.2657,  0.3371]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.2005,  0.4112, -0.2872,  ...,  0.1290,  0.4514,  0.3414],
         [-0.1999,  0.0860, -0.5153,  ...,  0.3916,  0.4107,  0.2008],
         [-0.2135,  0.5551, -0.5168,  ..., -0.1322,  0.4070,  0.4075],
         ...,
         [-0.3215,  0.1026, -0.2454,  ...,  0.2533,  0.5222,  0.2528],
         [-0.0363, -0.2433, -0.2383,  ...,  0.4081,  0.4931,  0.2604],
         [-0.0416,  0.1293,  0.1484,  ...,  0.0925,  0.2657,  0.3371]],

        [[-0.2005,  0.4112, -0.2872,  ...,  0.1290,  0.4514,  0.3414],
         [-0.3425,  0.2470, -0.4488,  ..., -0.1035,  0.4190,  0.5254],
         [-0.4660,  0.2110,  0.0730,  ...,  0.0310,  0.6527,  0.4932],
         ...,
         [-0.3491, -0.0945, -0.4201,  ...,  0.2475,  0.5849,  0.3557],
         [ 0.0488, -0.0947, -0.4573,  ...,  0.6100,  0.3797,  0.3675],
         [-0.0416,  0.1293,  0.1484,  ...,  0.0925,  0.2657,  0.3371]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.2005,  0.4112, -0.2872,  ..., -0.1032, -0.0486,  0.0346],
          [ 0.1361, -0.3992,  0.0221,  ...,  0.1290,  0.4514,  0.3414]],

         [[-0.1999,  0.0860, -0.5153,  ..., -0.5513, -0.5219, -0.1914],
          [ 0.3374, -0.2727,  0.3567,  ...,  0.3916,  0.4107,  0.2008]],

         [[-0.2135,  0.5551, -0.5168,  ..., -0.5669, -0.2263, -0.1473],
          [ 0.3070, -0.3759,  0.2568,  ..., -0.1322,  0.4070,  0.4075]],

         ...,

         [[-0.3215,  0.1026, -0.2454,  ..., -0.3795, -0.4719, -0.2736],
          [ 0.4383, -0.0532,  0.3590,  ...,  0.2533,  0.5222,  0.2528]],

         [[-0.0363, -0.2433, -0.2383,  ..., -0.0383, -0.0189, -0.4852],
          [ 0.0080, -0.1235,  0.3429,  ...,  0.4081,  0.4931,  0.2604]],

         [[-0.0416,  0.1293,  0.1484,  ..., -0.2649, -0.0021, -0.4983],
          [ 0.4329, -0.0340,  0.4973,  ...,  0.0925,  0.2657,  0.3371]]],


        [[[-0.2005,  0.4112, -0.2872,  ..., -0.1032, -0.0486,  0.0346],
          [ 0.1361, -0.3992,  0.0221,  ...,  0.1290,  0.4514,  0.3414]],

         [[-0.3425,  0.2470, -0.4488,  ..., -0.9216, -0.5638, -0.5498],
          [ 0.3720, -0.3046,  0.2391,  ..., -0.1035,  0.4190,  0.5254]],

         [[-0.4660,  0.2110,  0.0730,  ..., -0.2629, -0.1506, -0.1408],
          [ 0.2064, -0.5720, -0.1234,  ...,  0.0310,  0.6527,  0.4932]],

         ...,

         [[-0.3491, -0.0945, -0.4201,  ..., -0.2455, -0.4273, -0.1283],
          [ 0.3366, -0.2374,  0.2783,  ...,  0.2475,  0.5849,  0.3557]],

         [[ 0.0488, -0.0947, -0.4573,  ..., -0.2203, -0.0733, -0.0656],
          [ 0.2513, -0.1853,  0.2004,  ...,  0.6100,  0.3797,  0.3675]],

         [[-0.0416,  0.1293,  0.1484,  ..., -0.2649, -0.0021, -0.4983],
          [ 0.4329, -0.0340,  0.4973,  ...,  0.0925,  0.2657,  0.3371]]]],
       grad_fn=<ViewBackward0>)
tensor([[[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.7192, -1.4301,  0.1715,  ...,  1.0948, -1.6365,  0.9650],
         [-1.9657,  0.1727,  0.7456,  ...,  1.1198, -0.9969,  0.9112],
         ...,
         [-0.4332, -1.1145,  1.4794,  ...,  0.1403, -2.2722,  1.6160],
         [-1.6353, -1.5800,  0.9595,  ...,  0.2225, -0.1600,  0.2488],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]],

        [[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.1626, -1.7460, -0.1859,  ...,  1.8125, -2.3404,  1.1401],
         [-1.0802, -1.6798,  2.1436,  ...,  1.1471, -0.6465,  1.4981],
         ...,
         [ 1.1359, -1.1523, -0.0819,  ...,  0.1204, -1.2642,  1.8203],
         [-1.1290, -1.1690,  0.3605,  ...,  0.4243, -0.1978,  0.6577],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.7192, -1.4301,  0.1715,  ...,  1.0948, -1.6365,  0.9650],
         [-1.9657,  0.1727,  0.7456,  ...,  1.1198, -0.9969,  0.9112],
         ...,
         [-0.4332, -1.1145,  1.4794,  ...,  0.1403, -2.2722,  1.6160],
         [-1.6353, -1.5800,  0.9595,  ...,  0.2225, -0.1600,  0.2488],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]],

        [[ 0.3751, -0.3853,  0.1965,  ...,  0.6800, -0.2386,  2.6900],
         [-1.1626, -1.7460, -0.1859,  ...,  1.8125, -2.3404,  1.1401],
         [-1.0802, -1.6798,  2.1436,  ...,  1.1471, -0.6465,  1.4981],
         ...,
         [ 1.1359, -1.1523, -0.0819,  ...,  0.1204, -1.2642,  1.8203],
         [-1.1290, -1.1690,  0.3605,  ...,  0.4243, -0.1978,  0.6577],
         [ 0.0870, -1.0866,  1.6704,  ...,  0.7123, -0.7871,  3.0504]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[[ 0.3751, -0.3853,  0.1965,  ..., -1.0789, -1.3665,  0.3822],
          [ 0.6339, -1.4253,  1.8278,  ...,  0.6800, -0.2386,  2.6900]],

         [[-1.7192, -1.4301,  0.1715,  ..., -1.3837, -0.1853,  0.4532],
          [-1.3847, -0.0840,  1.2265,  ...,  1.0948, -1.6365,  0.9650]],

         [[-1.9657,  0.1727,  0.7456,  ..., -0.2237, -1.5358,  0.2253],
          [ 0.1228,  0.0352,  0.4116,  ...,  1.1198, -0.9969,  0.9112]],

         ...,

         [[-0.4332, -1.1145,  1.4794,  ..., -1.0549, -0.4699, -0.8138],
          [-0.6468,  0.0453,  1.0803,  ...,  0.1403, -2.2722,  1.6160]],

         [[-1.6353, -1.5800,  0.9595,  ...,  0.3656, -1.2632, -0.7188],
          [-0.9087, -1.1952,  1.8349,  ...,  0.2225, -0.1600,  0.2488]],

         [[ 0.0870, -1.0866,  1.6704,  ...,  0.4167, -1.9049,  0.1133],
          [ 1.9417,  0.0786,  0.9667,  ...,  0.7123, -0.7871,  3.0504]]],


        [[[ 0.3751, -0.3853,  0.1965,  ..., -1.0789, -1.3665,  0.3822],
          [ 0.6339, -1.4253,  1.8278,  ...,  0.6800, -0.2386,  2.6900]],

         [[-1.1626, -1.7460, -0.1859,  ..., -0.8641,  0.0093,  0.3981],
          [-1.6440, -0.6035,  1.4478,  ...,  1.8125, -2.3404,  1.1401]],

         [[-1.0802, -1.6798,  2.1436,  ...,  0.5640, -0.3284,  1.5421],
          [-0.6459,  0.3000,  0.7566,  ...,  1.1471, -0.6465,  1.4981]],

         ...,

         [[ 1.1359, -1.1523, -0.0819,  ...,  0.4814, -0.6913, -0.9617],
          [ 1.0799, -0.2296,  2.2318,  ...,  0.1204, -1.2642,  1.8203]],

         [[-1.1290, -1.1690,  0.3605,  ..., -0.4055, -1.5642, -1.1189],
          [-0.8859, -2.5340,  1.3438,  ...,  0.4243, -0.1978,  0.6577]],

         [[ 0.0870, -1.0866,  1.6704,  ...,  0.4167, -1.9049,  0.1133],
          [ 1.9417,  0.0786,  0.9667,  ...,  0.7123, -0.7871,  3.0504]]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.6960, -0.7233,  1.0027,  ..., -0.2414, -1.2033, -0.4546],
          [-0.7029, -0.8125,  0.8610,  ..., -0.4291, -1.1592, -0.2925],
          [-0.7163, -0.8257,  0.8543,  ..., -0.4203, -1.1693, -0.3031],
          ...,
          [-0.7143, -0.8246,  0.8360,  ..., -0.4500, -1.1180, -0.2664],
          [-0.7025, -0.8124,  0.8123,  ..., -0.4756, -1.1233, -0.2418],
          [-0.7208, -0.8213,  0.8440,  ..., -0.4532, -1.1634, -0.2902]],

         [[-0.5853,  0.1825,  0.7592,  ...,  0.5842, -0.9833,  0.9444],
          [-0.4010, -0.2355,  0.9945,  ...,  0.7371, -1.0119,  1.1443],
          [-0.4203, -0.1695,  0.9555,  ...,  0.7196, -1.0139,  1.1213],
          ...,
          [-0.3063, -0.3875,  1.0717,  ...,  0.7883, -1.0213,  1.2364],
          [-0.3339, -0.3219,  1.0357,  ...,  0.7653, -1.0272,  1.2064],
          [-0.4075, -0.2352,  0.9996,  ...,  0.7375, -1.0125,  1.1476]]],


        [[[-0.6878, -0.6352,  0.3987,  ..., -0.6813, -1.3243, -1.0531],
          [-0.4960, -0.9160,  0.5222,  ..., -0.2049, -1.0745, -0.4737],
          [-0.5163, -0.8884,  0.5049,  ..., -0.2257, -1.0899, -0.5256],
          ...,
          [-0.4986, -0.8688,  0.4959,  ..., -0.2240, -1.0931, -0.5232],
          [-0.4732, -0.8966,  0.5095,  ..., -0.2059, -1.0725, -0.4705],
          [-0.5344, -0.8682,  0.4888,  ..., -0.2654, -1.1140, -0.5926]],

         [[-0.7263, -0.3810,  0.9501,  ..., -0.0614, -0.9769,  1.2295],
          [-0.3226, -0.5113,  1.2332,  ...,  0.5543, -0.9762,  1.2908],
          [-0.3997, -0.5021,  1.1776,  ...,  0.4057, -0.9701,  1.2256],
          ...,
          [-0.3773, -0.5283,  1.2045,  ...,  0.4585, -0.9602,  1.2521],
          [-0.3941, -0.5139,  1.1914,  ...,  0.4363, -0.9706,  1.2336],
          [-0.4963, -0.4788,  1.1170,  ...,  0.2692, -0.9653,  1.2239]]]],
       grad_fn=<ScaledDotProductFlashAttentionForCpuBackward0>)
tensor([[[[-0.6960, -0.7233,  1.0027,  ..., -0.2414, -1.2033, -0.4546],
          [-0.5853,  0.1825,  0.7592,  ...,  0.5842, -0.9833,  0.9444]],

         [[-0.7029, -0.8125,  0.8610,  ..., -0.4291, -1.1592, -0.2925],
          [-0.4010, -0.2355,  0.9945,  ...,  0.7371, -1.0119,  1.1443]],

         [[-0.7163, -0.8257,  0.8543,  ..., -0.4203, -1.1693, -0.3031],
          [-0.4203, -0.1695,  0.9555,  ...,  0.7196, -1.0139,  1.1213]],

         ...,

         [[-0.7143, -0.8246,  0.8360,  ..., -0.4500, -1.1180, -0.2664],
          [-0.3063, -0.3875,  1.0717,  ...,  0.7883, -1.0213,  1.2364]],

         [[-0.7025, -0.8124,  0.8123,  ..., -0.4756, -1.1233, -0.2418],
          [-0.3339, -0.3219,  1.0357,  ...,  0.7653, -1.0272,  1.2064]],

         [[-0.7208, -0.8213,  0.8440,  ..., -0.4532, -1.1634, -0.2902],
          [-0.4075, -0.2352,  0.9996,  ...,  0.7375, -1.0125,  1.1476]]],


        [[[-0.6878, -0.6352,  0.3987,  ..., -0.6813, -1.3243, -1.0531],
          [-0.7263, -0.3810,  0.9501,  ..., -0.0614, -0.9769,  1.2295]],

         [[-0.4960, -0.9160,  0.5222,  ..., -0.2049, -1.0745, -0.4737],
          [-0.3226, -0.5113,  1.2332,  ...,  0.5543, -0.9762,  1.2908]],

         [[-0.5163, -0.8884,  0.5049,  ..., -0.2257, -1.0899, -0.5256],
          [-0.3997, -0.5021,  1.1776,  ...,  0.4057, -0.9701,  1.2256]],

         ...,

         [[-0.4986, -0.8688,  0.4959,  ..., -0.2240, -1.0931, -0.5232],
          [-0.3773, -0.5283,  1.2045,  ...,  0.4585, -0.9602,  1.2521]],


[I 2026-02-02 23:30:43,533] Trial 0 finished with value: 0.86616 and parameters: {'num_layers': 1, 'num_heads': 2, 'hidden_size': 0, 'intermediate_size': 4, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}. Best is trial 0 with value: 0.86616.
/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.linear.Linear'> which is of type type.
  warnings.warn(message)
/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/optuna/distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'chop.nn.modules.identity.Identity'> which is of type type.
  warnings.warn(message)

trial config:  {}
chosen_idx =  0
search_space[param][chosen_idx] 2
chosen_idx =  3
search_space[param][chosen_idx] 16
chosen_idx =  2
search_space[param][chosen_idx] 256
chosen_idx =  3
search_space[param][chosen_idx] 1536
trial config:  {'num_layers': 0, 'num_heads': 3, 'hidden_size': 2, 'intermediate_size': 3, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}

/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.
INFO     Getting dummy input for prajjwal1/bert-tiny.

tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.6536e+00,  6.7538e-01, -2.3739e-01,  ...,  1.0647e+00,
          -1.7165e+00,  2.1832e-01],
         [-1.3772e+00, -4.8628e-01, -1.5871e+00,  ..., -2.2881e-01,
           3.6952e-01,  9.9714e-01],
         ...,
         [ 4.5179e-01,  7.6933e-01, -2.0182e+00,  ..., -2.9614e+00,
           1.5173e+00,  1.2626e+00],
         [ 6.3908e-02,  6.6813e-02, -1.5356e+00,  ..., -3.0560e-01,
           5.1272e-02,  1.7027e+00],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]],

        [[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.2809e+00,  1.4127e-01, -1.0956e+00,  ..., -1.0001e+00,
          -1.6244e+00, -2.0880e-01],
         [-1.0949e+00, -1.3750e+00, -4.9947e-01,  ...,  5.0237e-01,
          -3.2456e-02,  6.8538e-01],
         ...,
         [-6.6626e-01,  4.9927e-01, -1.6310e+00,  ..., -2.5170e+00,
          -3.7489e-01,  9.6461e-03],
         [-3.1505e-01, -1.1339e+00, -7.8567e-01,  ...,  1.0044e-01,
          -1.0040e+00, -2.3245e-01],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]]], grad_fn=<NativeLayerNormBackward0>)
tensor([[[-0.5940, -0.5570,  0.3415,  ...,  0.0785,  0.0971,  1.6795],
         [-0.3715, -0.3381, -0.2060,  ..., -0.0820, -0.1487,  0.0442],
         [-0.3807, -0.3438, -0.2387,  ..., -0.2692, -0.0207,  0.1797],
         ...,
         [-0.6628, -0.6110,  0.1501,  ..., -0.0447,  0.7668,  0.4158],
         [-0.5243, -0.5386,  0.5577,  ..., -0.7797, -0.0601,  0.3776],
         [-0.3999, -0.1413, -0.0254,  ..., -0.0157,  0.2300,  0.0194]],

        [[-0.5940, -0.5570,  0.3415,  ...,  0.0785,  0.0971,  1.6795],
         [-0.5878, -0.0815,  0.1441,  ..., -0.2911, -0.1707,  0.4840],
         [-0.1154, -0.1902,  0.0780,  ..., -0.0646, -0.1262,  0.4953],
         ...,
         [-0.8130, -0.3555,  0.4206,  ..., -0.3817,  0.2776,  0.3706],
         [-0.4134, -0.3306,  0.2900,  ..., -0.0966, -0.2594,  0.4970],
         [-0.3999, -0.1413, -0.0254,  ..., -0.0157,  0.2300,  0.0194]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.5940, -0.5570,  0.3415,  ...,  0.0785,  0.0971,  1.6795],
         [-0.3715, -0.3381, -0.2060,  ..., -0.0820, -0.1487,  0.0442],
         [-0.3807, -0.3438, -0.2387,  ..., -0.2692, -0.0207,  0.1797],
         ...,
         [-0.6628, -0.6110,  0.1501,  ..., -0.0447,  0.7668,  0.4158],
         [-0.5243, -0.5386,  0.5577,  ..., -0.7797, -0.0601,  0.3776],
         [-0.3999, -0.1413, -0.0254,  ..., -0.0157,  0.2300,  0.0194]],

        [[-0.5940, -0.5570,  0.3415,  ...,  0.0785,  0.0971,  1.6795],
         [-0.5878, -0.0815,  0.1441,  ..., -0.2911, -0.1707,  0.4840],
         [-0.1154, -0.1902,  0.0780,  ..., -0.0646, -0.1262,  0.4953],
         ...,
         [-0.8130, -0.3555,  0.4206,  ..., -0.3817,  0.2776,  0.3706],
         [-0.4134, -0.3306,  0.2900,  ..., -0.0966, -0.2594,  0.4970],
         [-0.3999, -0.1413, -0.0254,  ..., -0.0157,  0.2300,  0.0194]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.5940, -0.5570,  0.3415,  ..., -1.3992, -0.1085, -0.6869],
          [-0.7443,  1.2953,  1.0367,  ...,  0.0785,  0.0971,  1.6795]],

         [[-0.3715, -0.3381, -0.2060,  ..., -0.1111, -0.5669,  0.0793],
          [-0.4792,  0.1353,  0.6090,  ..., -0.0820, -0.1487,  0.0442]],

         [[-0.3807, -0.3438, -0.2387,  ..., -0.3760,  0.3845, -0.3566],
          [ 0.0405,  0.9475,  0.2622,  ..., -0.2692, -0.0207,  0.1797]],

         ...,

         [[-0.6628, -0.6110,  0.1501,  ..., -0.9521, -0.6295, -0.2581],
          [-0.3422,  0.1066,  0.3166,  ..., -0.0447,  0.7668,  0.4158]],

         [[-0.5243, -0.5386,  0.5577,  ..., -0.6505, -0.4097, -0.4677],
          [-0.3278,  0.0551, -0.1473,  ..., -0.7797, -0.0601,  0.3776]],

         [[-0.3999, -0.1413, -0.0254,  ..., -0.4534,  0.3001, -0.1605],
          [ 0.2792,  0.1909,  0.5697,  ..., -0.0157,  0.2300,  0.0194]]],


        [[[-0.5940, -0.5570,  0.3415,  ..., -1.3992, -0.1085, -0.6869],
          [-0.7443,  1.2953,  1.0367,  ...,  0.0785,  0.0971,  1.6795]],

         [[-0.5878, -0.0815,  0.1441,  ..., -0.4458, -1.0111, -0.1957],
          [-0.4898,  0.5586,  0.4980,  ..., -0.2911, -0.1707,  0.4840]],

         [[-0.1154, -0.1902,  0.0780,  ..., -0.2360,  0.2945, -0.6467],
          [-0.0035,  0.6890,  0.6808,  ..., -0.0646, -0.1262,  0.4953]],

         ...,

         [[-0.8130, -0.3555,  0.4206,  ..., -0.3431, -0.0178, -0.6305],
          [ 0.0739,  0.3554,  0.4988,  ..., -0.3817,  0.2776,  0.3706]],

         [[-0.4134, -0.3306,  0.2900,  ..., -0.8305, -0.8360, -0.0243],
          [-0.1872,  0.0871, -0.1566,  ..., -0.0966, -0.2594,  0.4970]],

         [[-0.3999, -0.1413, -0.0254,  ..., -0.4534,  0.3001, -0.1605],
          [ 0.2792,  0.1909,  0.5697,  ..., -0.0157,  0.2300,  0.0194]]]],
       grad_fn=<ViewBackward0>)
tensor([[[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.6536e+00,  6.7538e-01, -2.3739e-01,  ...,  1.0647e+00,
          -1.7165e+00,  2.1832e-01],
         [-1.3772e+00, -4.8628e-01, -1.5871e+00,  ..., -2.2881e-01,
           3.6952e-01,  9.9714e-01],
         ...,
         [ 4.5179e-01,  7.6933e-01, -2.0182e+00,  ..., -2.9614e+00,
           1.5173e+00,  1.2626e+00],
         [ 6.3908e-02,  6.6813e-02, -1.5356e+00,  ..., -3.0560e-01,
           5.1272e-02,  1.7027e+00],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]],

        [[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.2809e+00,  1.4127e-01, -1.0956e+00,  ..., -1.0001e+00,
          -1.6244e+00, -2.0880e-01],
         [-1.0949e+00, -1.3750e+00, -4.9947e-01,  ...,  5.0237e-01,
          -3.2456e-02,  6.8538e-01],
         ...,
         [-6.6626e-01,  4.9927e-01, -1.6310e+00,  ..., -2.5170e+00,
          -3.7489e-01,  9.6461e-03],
         [-3.1505e-01, -1.1339e+00, -7.8567e-01,  ...,  1.0044e-01,
          -1.0040e+00, -2.3245e-01],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]]], grad_fn=<NativeLayerNormBackward0>)
tensor([[[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.6536e+00,  6.7538e-01, -2.3739e-01,  ...,  1.0647e+00,
          -1.7165e+00,  2.1832e-01],
         [-1.3772e+00, -4.8628e-01, -1.5871e+00,  ..., -2.2881e-01,
           3.6952e-01,  9.9714e-01],
         ...,
         [ 4.5179e-01,  7.6933e-01, -2.0182e+00,  ..., -2.9614e+00,
           1.5173e+00,  1.2626e+00],
         [ 6.3908e-02,  6.6813e-02, -1.5356e+00,  ..., -3.0560e-01,
           5.1272e-02,  1.7027e+00],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]],

        [[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ..., -9.7728e-01,
          -1.3821e+00, -3.6705e-01],
         [-1.2809e+00,  1.4127e-01, -1.0956e+00,  ..., -1.0001e+00,
          -1.6244e+00, -2.0880e-01],
         [-1.0949e+00, -1.3750e+00, -4.9947e-01,  ...,  5.0237e-01,
          -3.2456e-02,  6.8538e-01],
         ...,
         [-6.6626e-01,  4.9927e-01, -1.6310e+00,  ..., -2.5170e+00,
          -3.7489e-01,  9.6461e-03],
         [-3.1505e-01, -1.1339e+00, -7.8567e-01,  ...,  1.0044e-01,
          -1.0040e+00, -2.3245e-01],
         [-3.0386e-01, -2.1105e-01, -2.1816e-01,  ..., -1.2037e-03,
          -1.1367e+00, -6.5547e-01]]], grad_fn=<NativeLayerNormBackward0>)
tensor([[[[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ...,  4.1269e-01,
            6.0945e-01, -5.2101e-01],
          [ 2.9169e+00, -6.3175e-01,  3.4328e-01,  ..., -9.7728e-01,
           -1.3821e+00, -3.6705e-01]],

         [[-1.6536e+00,  6.7538e-01, -2.3739e-01,  ...,  9.7076e-01,
           -3.4967e-01, -9.5892e-01],
          [ 2.2364e+00, -8.5398e-01,  1.7226e+00,  ...,  1.0647e+00,
           -1.7165e+00,  2.1832e-01]],

         [[-1.3772e+00, -4.8628e-01, -1.5871e+00,  ..., -1.0233e+00,
            2.7486e-01,  3.3656e-01],
          [ 7.6121e-01,  7.8221e-01,  1.1863e+00,  ..., -2.2881e-01,
            3.6952e-01,  9.9714e-01]],

         ...,

         [[ 4.5179e-01,  7.6933e-01, -2.0182e+00,  ...,  1.3131e+00,
            1.3860e+00,  1.8347e+00],
          [ 6.2772e-01,  3.3065e-01, -3.3362e-01,  ..., -2.9614e+00,
            1.5173e+00,  1.2626e+00]],

         [[ 6.3908e-02,  6.6813e-02, -1.5356e+00,  ..., -1.6719e-01,
           -1.8649e-01,  3.1200e-01],
          [ 1.9477e+00, -1.1664e+00,  3.1129e-01,  ..., -3.0560e-01,
            5.1272e-02,  1.7027e+00]],

         [[-3.0386e-01, -2.1105e-01, -2.1816e-01,  ...,  2.0515e-01,
            8.5780e-01,  6.8119e-01],
          [ 1.1320e+00,  1.1955e+00,  5.8645e-01,  ..., -1.2037e-03,
           -1.1367e+00, -6.5547e-01]]],


        [[[-1.2723e+00, -3.7050e-03, -7.4347e-01,  ...,  4.1269e-01,
            6.0945e-01, -5.2101e-01],
          [ 2.9169e+00, -6.3175e-01,  3.4328e-01,  ..., -9.7728e-01,
           -1.3821e+00, -3.6705e-01]],

         [[-1.2809e+00,  1.4127e-01, -1.0956e+00,  ...,  2.0520e+00,
           -1.4516e+00, -2.2871e-01],
          [ 1.1557e+00, -1.3868e+00,  1.1062e-01,  ..., -1.0001e+00,
           -1.6244e+00, -2.0880e-01]],

         [[-1.0949e+00, -1.3750e+00, -4.9947e-01,  ..., -2.1414e-01,
           -3.6571e-01, -2.6517e-01],
          [ 1.1833e+00, -4.6126e-02,  3.1451e-01,  ...,  5.0237e-01,
           -3.2456e-02,  6.8538e-01]],

         ...,

         [[-6.6626e-01,  4.9927e-01, -1.6310e+00,  ...,  2.0765e+00,
            4.0170e-01,  1.4444e+00],
          [ 1.1996e-01,  3.6130e-01,  1.1048e+00,  ..., -2.5170e+00,
           -3.7489e-01,  9.6461e-03]],

         [[-3.1505e-01, -1.1339e+00, -7.8567e-01,  ...,  7.9522e-01,
           -1.0170e+00, -8.8202e-01],
          [ 1.0586e+00, -1.0394e+00,  1.4010e+00,  ...,  1.0044e-01,
           -1.0040e+00, -2.3245e-01]],

         [[-3.0386e-01, -2.1105e-01, -2.1816e-01,  ...,  2.0515e-01,
            8.5780e-01,  6.8119e-01],
          [ 1.1320e+00,  1.1955e+00,  5.8645e-01,  ..., -1.2037e-03,
           -1.1367e+00, -6.5547e-01]]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.0323,  0.1605, -0.1185,  ..., -0.7637,  0.0196,  0.0564],
         [-0.2759, -0.3696, -0.3752,  ..., -0.6592,  0.0663, -0.2761],
         [-0.0032, -0.4272, -0.8175,  ..., -0.0423, -0.0519, -0.1066],
         ...,
         [ 0.2035,  0.2884, -0.9282,  ..., -0.6716,  0.2420,  0.1745],
         [ 0.2551,  0.0154, -0.6706,  ..., -0.2434,  0.0791,  0.1651],
         [-0.1622,  0.1082, -0.5112,  ..., -0.6507, -0.0741,  0.0108]],

        [[ 0.0323,  0.1605, -0.1185,  ..., -0.7637,  0.0196,  0.0564],
         [-0.3881, -0.0783, -0.6216,  ..., -0.8229,  0.0940,  0.0519],
         [ 0.0106, -0.6513, -0.9078,  ..., -0.3637,  0.5246,  0.1939],
         ...,
         [ 0.0707,  0.3715, -0.6281,  ..., -0.7223,  0.4937,  0.0079],
         [-0.1668,  0.0252,  0.1466,  ..., -0.1905,  0.0374,  0.3171],
         [-0.1622,  0.1082, -0.5112,  ..., -0.6507, -0.0741,  0.0108]]],
       grad_fn=<ViewBackward0>)
tensor([[[ 0.0323,  0.1605, -0.1185,  ..., -0.7637,  0.0196,  0.0564],
         [-0.2759, -0.3696, -0.3752,  ..., -0.6592,  0.0663, -0.2761],
         [-0.0032, -0.4272, -0.8175,  ..., -0.0423, -0.0519, -0.1066],
         ...,
         [ 0.2035,  0.2884, -0.9282,  ..., -0.6716,  0.2420,  0.1745],
         [ 0.2551,  0.0154, -0.6706,  ..., -0.2434,  0.0791,  0.1651],
         [-0.1622,  0.1082, -0.5112,  ..., -0.6507, -0.0741,  0.0108]],

        [[ 0.0323,  0.1605, -0.1185,  ..., -0.7637,  0.0196,  0.0564],
         [-0.3881, -0.0783, -0.6216,  ..., -0.8229,  0.0940,  0.0519],
         [ 0.0106, -0.6513, -0.9078,  ..., -0.3637,  0.5246,  0.1939],
         ...,
         [ 0.0707,  0.3715, -0.6281,  ..., -0.7223,  0.4937,  0.0079],
         [-0.1668,  0.0252,  0.1466,  ..., -0.1905,  0.0374,  0.3171],
         [-0.1622,  0.1082, -0.5112,  ..., -0.6507, -0.0741,  0.0108]]],
       grad_fn=<ViewBackward0>)
tensor([[[[ 0.0323,  0.1605, -0.1185,  ...,  0.1315,  0.3471, -0.0348],
          [-0.3098,  0.5896,  0.1670,  ..., -0.7637,  0.0196,  0.0564]],

         [[-0.2759, -0.3696, -0.3752,  ...,  0.7897,  0.2801,  0.0288],
          [-0.0510,  0.1268, -0.0690,  ..., -0.6592,  0.0663, -0.2761]],

         [[-0.0032, -0.4272, -0.8175,  ..., -0.0533,  0.0755,  0.0352],
          [-0.1018,  0.6929,  0.8159,  ..., -0.0423, -0.0519, -0.1066]],

         ...,

         [[ 0.2035,  0.2884, -0.9282,  ...,  0.0406, -0.1757,  0.2037],
          [ 0.5677, -0.1472,  0.3474,  ..., -0.6716,  0.2420,  0.1745]],

         [[ 0.2551,  0.0154, -0.6706,  ...,  0.6997,  0.3964,  0.5076],
          [ 0.3937,  0.6541,  0.4104,  ..., -0.2434,  0.0791,  0.1651]],

         [[-0.1622,  0.1082, -0.5112,  ..., -0.2115,  0.2004, -0.2113],
          [-0.1645,  0.1920, -0.0551,  ..., -0.6507, -0.0741,  0.0108]]],


        [[[ 0.0323,  0.1605, -0.1185,  ...,  0.1315,  0.3471, -0.0348],
          [-0.3098,  0.5896,  0.1670,  ..., -0.7637,  0.0196,  0.0564]],

         [[-0.3881, -0.0783, -0.6216,  ...,  0.1873, -0.1267,  0.1969],
          [ 0.2286, -0.0294,  0.3018,  ..., -0.8229,  0.0940,  0.0519]],

         [[ 0.0106, -0.6513, -0.9078,  ...,  0.1963,  0.2620,  0.5491],
          [ 0.3415,  0.8712,  0.9393,  ..., -0.3637,  0.5246,  0.1939]],

         ...,

         [[ 0.0707,  0.3715, -0.6281,  ..., -0.2097, -0.4325,  0.0062],
          [ 0.5013, -0.4166,  0.4355,  ..., -0.7223,  0.4937,  0.0079]],

         [[-0.1668,  0.0252,  0.1466,  ...,  0.2311, -0.5496,  0.1464],
          [ 0.0517,  0.3679, -0.2642,  ..., -0.1905,  0.0374,  0.3171]],

         [[-0.1622,  0.1082, -0.5112,  ..., -0.2115,  0.2004, -0.2113],
          [-0.1645,  0.1920, -0.0551,  ..., -0.6507, -0.0741,  0.0108]]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.0661, -0.1915, -0.5039,  ...,  0.5512,  0.1800,  0.1409],
          [-0.0376, -0.1098, -0.5259,  ...,  0.3835,  0.0982,  0.1171],
          [-0.0364, -0.1420, -0.5174,  ...,  0.3976,  0.0917,  0.1023],
          ...,
          [-0.0422, -0.1528, -0.5292,  ...,  0.4279,  0.1096,  0.1242],
          [-0.0424, -0.1158, -0.5259,  ...,  0.3739,  0.1146,  0.1302],
          [-0.0037, -0.0762, -0.5320,  ...,  0.3699,  0.1268,  0.1476]],

         [[-0.0553,  0.6385,  0.7442,  ..., -0.0915, -0.0330, -0.0816],
          [ 0.1212,  0.3819,  0.3972,  ..., -0.3076,  0.0330, -0.0568],
          [ 0.1107,  0.3374,  0.3416,  ..., -0.3595,  0.0492, -0.0239],
          ...,
          [ 0.0973,  0.4192,  0.4377,  ..., -0.2878,  0.0295, -0.0351],
          [ 0.1004,  0.3730,  0.4206,  ..., -0.3269,  0.0418, -0.0141],
          [ 0.0861,  0.4198,  0.4164,  ..., -0.3290,  0.0371, -0.0102]]],


        [[[-0.0934,  0.0126, -0.1824,  ...,  0.0064, -0.2727, -0.0330],
          [-0.0967,  0.0226, -0.2599,  ..., -0.0125, -0.2333, -0.0099],
          [-0.0873,  0.0341, -0.2754,  ..., -0.0152, -0.2262,  0.0019],
          ...,
          [-0.1098,  0.0384, -0.2826,  ..., -0.0380, -0.2275, -0.0098],
          [-0.0849, -0.0329, -0.3042,  ...,  0.0353, -0.1929,  0.0500],
          [-0.1025,  0.0170, -0.2511,  ..., -0.0151, -0.2241, -0.0247]],

         [[ 0.1953,  0.4373,  0.5813,  ..., -0.3235,  0.2248,  0.1222],
          [ 0.1741,  0.2374,  0.3523,  ..., -0.3802,  0.0903,  0.0913],
          [ 0.1538,  0.2016,  0.2734,  ..., -0.3945,  0.0666,  0.0863],
          ...,
          [ 0.1676,  0.1656,  0.2822,  ..., -0.3982,  0.0771,  0.0922],
          [ 0.1365,  0.2373,  0.3586,  ..., -0.3896,  0.0793,  0.1039],
          [ 0.1255,  0.2132,  0.3509,  ..., -0.3729,  0.0289,  0.1422]]]],
       grad_fn=<ScaledDotProductFlashAttentionForCpuBackward0>)
tensor([[[[-0.0661, -0.1915, -0.5039,  ...,  0.5512,  0.1800,  0.1409],
          [-0.0553,  0.6385,  0.7442,  ..., -0.0915, -0.0330, -0.0816]],

         [[-0.0376, -0.1098, -0.5259,  ...,  0.3835,  0.0982,  0.1171],
          [ 0.1212,  0.3819,  0.3972,  ..., -0.3076,  0.0330, -0.0568]],


INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: classifier

[I 2026-02-02 23:33:21,803] Trial 1 finished with value: 0.87392 and parameters: {'num_layers': 0, 'num_heads': 3, 'hidden_size': 2, 'intermediate_size': 3, 'bert.encoder.layer.0.attention.self.query_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.0.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.0.attention.output.dense_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.self.query_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.key_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.encoder.layer.1.attention.self.value_type': <class 'torch.nn.modules.linear.Linear'>, 'bert.encoder.layer.1.attention.output.dense_type': <class 'chop.nn.modules.identity.Identity'>, 'bert.pooler.dense_type': <class 'chop.nn.modules.identity.Identity'>}. Best is trial 1 with value: 0.87392.

The final model will be given by 

```py
model = study.best_trial.user_attrs["model"].cpu()
mg = MaseGraph(model)
mg, _ = pipe(mg, compression_config)
```

# Lab 1

In [ ]:
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

from pathlib import Path
from chop import MaseGraph
from chop.tools import get_tokenized_dataset, get_trainer
import chop.passes as passes
import json

# setting data_in_width
widths = [i for i in range(4, 33)]
print(f"Widths to be evaluated: {widths}")

# dictionary for storing eval results 
eval_dict = {}

"""Loop starts"""
for width in widths:
    # width = 4

    # Load starting model
    mg = MaseGraph.from_checkpoint(f"{Path.home()}/tutorial_2_lora")

    # Load dataset, tokenizer
    dataset, tokenizer = get_tokenized_dataset(
        dataset=dataset_name,
        checkpoint=tokenizer_checkpoint,
        return_tokenizer=True,
    )


    # PTQ
    quantization_config = {
        "by": "type",
        "default": {
            "config": {
                "name": None,
            }
        },
        "linear": {
            "config": {
                "name": "integer",
                # data
                "data_in_width": 8,
                "data_in_frac_width": 4,
                # weight
                "weight_width": 8,
                "weight_frac_width": 4,
                # bias
                "bias_width": 8,
                "bias_frac_width": 4,
            }
        },
    }
    # Overwrite these with numbers from 4 to 32
    quantization_config["linear"]["config"]["data_in_width"] =  width
    quantization_config["linear"]["config"]["weight_width"] =   width
    quantization_config["linear"]["config"]["bias_width"] =     width

    mg, _ = passes.quantize_transform_pass(
        mg,
        pass_args=quantization_config,
    )

    ## Evaluate PTQ
    trainer = get_trainer(
        model=mg.model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
    )
    eval_results = trainer.evaluate()
    print(f"PTQ: Evaluation accuracy for width {width}: {eval_results['eval_accuracy']}")
    mg.export(f"{Path.home()}/tutorial_3_ptq_width_{width}")

    # QAT
    trainer.train()
    eval_results = trainer.evaluate()
    print(f"QAT: Evaluation accuracy for width {width}: {eval_results['eval_accuracy']}")
    mg.export(f"{Path.home()}/tutorial_4_qat_width_{width}")

    
    # Save eval results
    eval_dict[width] = eval_results['eval_accuracy']
    json.dump(eval_dict, open("task_3_eval_dict.json", "w"))

/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/ism/ADL/mase/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Widths to be evaluated: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]

WARNING  Node finfo not found in loaded metadata.
WARNING  Node getattr_2 not found in loaded metadata.
INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Exporting MaseGraph to /home/ism/tutorial_3_ptq_width_4.pt, /home/ism/tutorial_3_ptq_width_4.mz
INFO     Exporting GraphModule to /home/ism/tutorial_3_ptq_width_4.pt
INFO     Saving full model format
INFO     Exporting MaseMetadata to /home/ism/tutorial_3_ptq_width_4.mz

PTQ: Evaluation accuracy for width 4: 0.66356

INFO     Exporting MaseGraph to /home/ism/tutorial_4_qat_width_4.pt, /home/ism/tutorial_4_qat_width_4.mz
INFO     Exporting GraphModule to /home/ism/tutorial_4_qat_width_4.pt
INFO     Saving full model format
INFO     Exporting MaseMetadata to /home/ism/tutorial_4_qat_width_4.mz

QAT: Evaluation accuracy for width 4: 0.79256

WARNING  Node finfo not found in loaded metadata.
WARNING  Node getattr_2 not found in loaded metadata.
INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.
/home/ism/ADL/mase/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

KeyboardInterrupt: